from sqlalchemy.orm import relationship, sessionmaker, declarative_base
from sqlalchemy import Column, Integer, String, Boolean, DateTime, ForeignKey, Integer, LargeBinary, Numeric

Base = declarative_base()

class LoRAModel(Base):
    __tablename__ = "lora_models"
    id = Column(Integer, primary_key=True)
    filepath = Column(String)
    filename = Column(String)
    preview_image = Column(LargeBinary, nullable=True)
    display_name = Column(String, nullable=True)
    author = Column(String, nullable=True)
    source = Column(String, nullable=True)
    keywords = Column(String, nullable=True)
    description = Column(String, nullable=True)
    rating = Column(Integer, nullable=True)
    tags = Column(String, nullable=True)
    model_hash = Column(String, nullable=True)
    legacy_hash = Column(String, nullable=True)
    session_id = Column(Integer, nullable=True)
    training_started_at = Column(DateTime, nullable=True)
    output_name = Column(String, nullable=True)
    learning_rate = Column(Numeric, nullable=True)
    text_encoder_lr = Column(Numeric, nullable=True)
    unet_lr = Column(Numeric, nullable=True)
    num_train_images = Column(Integer, nullable=True)
    num_reg_images = Column(Integer, nullable=True)
    num_batches_per_epoch = Column(Integer, nullable=True)
    num_epochs = Column(Integer, nullable=True)
    epoch = Column(Integer, nullable=True)
    batch_size_per_device = Column(Integer, nullable=True)
    total_batch_size = Column(Integer, nullable=True)
    gradient_checkpointing = Column(Boolean, nullable=True)
    gradient_accumulation_steps = Column(Integer, nullable=True)
    max_train_steps = Column(Integer, nullable=True)
    lr_warmup_steps = Column(Integer, nullable=True)
    lr_scheduler = Column(String, nullable=True)
    network_module = Column(String, nullable=True)
    network_dim = Column(Integer, nullable=True)
    network_alpha = Column(Numeric, nullable=True)
    mixed_precision = Column(Boolean, nullable=True)
    full_fp16 = Column(Boolean, nullable=True)
    v2 = Column(Boolean, nullable=True)
    resolution = Column(String, nullable=True)
    clip_skip = Column(Integer, nullable=True)
    max_token_length = Column(Integer, nullable=True)
    color_aug = Column(Boolean, nullable=True)
    flip_aug = Column(Boolean, nullable=True)
    random_crop = Column(Boolean, nullable=True)
    shuffle_caption = Column(Boolean, nullable=True)
    cache_latents = Column(Boolean, nullable=True)
    enable_bucket = Column(Boolean, nullable=True)
    min_bucket_reso = Column(Integer, nullable=True)
    max_bucket_reso = Column(Integer, nullable=True)
    seed = Column(Integer, nullable=True)
    keep_tokens = Column(Boolean, nullable=True)
    noise_offset = Column(Numeric, nullable=True)
    dataset_dirs = Column(String, nullable=True)
    reg_dataset_dirs = Column(String, nullable=True)
    sd_model_name = Column(String, nullable=True)
    sd_model_hash = Column(String, nullable=True)
    sd_new_model_hash = Column(String, nullable=True)
    sd_vae_name = Column(String, nullable=True)
    sd_vae_hash = Column(String, nullable=True)
    sd_new_vae_hash = Column(String, nullable=True)

    vae_name = Column(String, nullable=True)
    training_comment = Column(String, nullable=True)
    bucket_info = Column(String, nullable=True)
    sd_scripts_commit_hash = Column(String, nullable=True)
